version: "3.4"

services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        environment:
          Server: "db"
          Database: "Master"
          Port: "1433"
          user: "sa"
          Password: "S3cur3P@ssW0rd!"
          
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"
